ctng_cpu_arch:
  - armv7l
ctng_vendor:
  - conda_cos7
  #- conda
ctng_target_platform:
  - linux-armv7l
c_compiler:
  - gcc
c_compiler_version:
  - 11
cxx_compiler:       # [linux]
  - g++   # [linux]
zip_keys:
  -
    - ctng_cpu_arch
    - ctng_vendor
    - ctng_target_platform
