# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-11
  strategy:
    matrix:
      osx_64_ctng_cpu_archaarch64ctng_target_platformlinux-aarch64ctng_vendorconda_cos7:
        CONFIG: osx_64_ctng_cpu_archaarch64ctng_target_platformlinux-aarch64ctng_vendorconda_cos7
        UPLOAD_PACKAGES: 'True'
      osx_64_ctng_cpu_archpowerpc64lectng_target_platformlinux-ppc64lectng_vendorconda_cos7:
        CONFIG: osx_64_ctng_cpu_archpowerpc64lectng_target_platformlinux-ppc64lectng_vendorconda_cos7
        UPLOAD_PACKAGES: 'True'
      osx_64_ctng_cpu_archs390xctng_target_platformlinux-s390xctng_vendorconda_cos7:
        CONFIG: osx_64_ctng_cpu_archs390xctng_target_platformlinux-s390xctng_vendorconda_cos7
        UPLOAD_PACKAGES: 'True'
      osx_64_ctng_cpu_archx86_64ctng_target_platformlinux-64ctng_vendorconda_cos6:
        CONFIG: osx_64_ctng_cpu_archx86_64ctng_target_platformlinux-64ctng_vendorconda_cos6
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)